---
version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/ddclient:/config
    restart: unless-stopped
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - URL=${MYDOMAIN?No domain specified!}
        # - SUBDOMAINS=www,
        # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true  # change to 'false' for use in production
    volumes:
      - ${BASE_DIR?Base directory not specified!}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/nextcloud/config:/config
      - ${BASE_DIR?Base directory not specified!}/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW?Database root password is missing!}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${DB_NEXTCLOUD_PW?Database password for nextcloud user is missing!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/mariadb:/config
    restart: unless-stopped
  collabora:
    image: collabora/code
    container_name: collabora
    environment:
      - aliasgroup1=https://${MYDOMAIN}:443
      - username=admin
      - password=${COLLABORA_ADMIN_PW?Collabora password not specified!}
      - DONT_GEN_SSL_CERT=true
      - server_name=${MYDOMAIN}
      - dictionaries="de_DE en_GB en_US"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:logging.level=error --o:net.service_root=/collabora"
    restart: unless-stopped
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    user: ${PUID?PUID is not known!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/gitea/data:/var/lib/gitea
      - ${BASE_DIR?Base directory not specified!}/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD?gitea database password not specified!}
    restart: unless-stopped
