---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - URL=${MYDOMAIN?No domain specified!}
        # - SUBDOMAINS=www,
        # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true  # change to 'false' for use in production
    volumes:
      - ${BASE_DIR?Base directory not specified!}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/nextcloud/config:/config
      - ${BASE_DIR?Base directory not specified!}/nextcloud/data:/config
    restart: unless-stopped
