---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - URL=${MYDOMAIN?No domain specified!}
        # - SUBDOMAINS=www,
        # - EXTRA_DOMAINS=
      - VALIDATION=http
      - STAGING=true  # change to 'false' for use in production
    volumes:
      - ${BASE_DIR?Base directory not specified!}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/nextcloud/config:/config
      - ${BASE_DIR?Base directory not specified!}/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID?PUID is not known!}
      - PGID=${PGID?PGID is not known!}
      - TZ=${TIMEZONE?No timezone specified!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW?Database root password is missing!}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${DB_NEXTCLOUD_PW?Database password for nextcloud user is missing!}
    volumes:
      - ${BASE_DIR?Base directory not specified!}/mariadb:/config
    restart: unless-stopped
